var annotated_dup =
[
    [ "CGTEST", "namespace_c_g_t_e_s_t.html", [
      [ "GURobotsTests", "class_c_g_t_e_s_t_1_1_g_u_robots_tests.html", "class_c_g_t_e_s_t_1_1_g_u_robots_tests" ],
      [ "GUWrapperTests", "class_c_g_t_e_s_t_1_1_g_u_wrapper_tests.html", "class_c_g_t_e_s_t_1_1_g_u_wrapper_tests" ],
      [ "NaoV5CPPTests", "class_c_g_t_e_s_t_1_1_nao_v5_c_p_p_tests.html", "class_c_g_t_e_s_t_1_1_nao_v5_c_p_p_tests" ]
    ] ],
    [ "GU", "namespace_g_u.html", [
      [ "NaoV5", "struct_g_u_1_1_nao_v5.html", "struct_g_u_1_1_nao_v5" ],
      [ "PitchJoint", "struct_g_u_1_1_pitch_joint.html", "struct_g_u_1_1_pitch_joint" ],
      [ "PitchRollJoint", "struct_g_u_1_1_pitch_roll_joint.html", "struct_g_u_1_1_pitch_roll_joint" ],
      [ "PitchYawJoint", "struct_g_u_1_1_pitch_yaw_joint.html", "struct_g_u_1_1_pitch_yaw_joint" ],
      [ "SoccerLocations", "struct_g_u_1_1_soccer_locations.html", "struct_g_u_1_1_soccer_locations" ],
      [ "YawJoint", "struct_g_u_1_1_yaw_joint.html", "struct_g_u_1_1_yaw_joint" ],
      [ "YawRollJoint", "struct_g_u_1_1_yaw_roll_joint.html", "struct_g_u_1_1_yaw_roll_joint" ],
      [ "YPJoint", "struct_g_u_1_1_y_p_joint.html", "struct_g_u_1_1_y_p_joint" ]
    ] ],
    [ "cam_coord_to_px_coord_Fake", "structcam__coord__to__px__coord___fake.html", "structcam__coord__to__px__coord___fake" ],
    [ "cartesian_coord_to_rr_coord_Fake", "structcartesian__coord__to__rr__coord___fake.html", "structcartesian__coord__to__rr__coord___fake" ],
    [ "cartesian_coord_to_rr_coord_from_source_Fake", "structcartesian__coord__to__rr__coord__from__source___fake.html", "structcartesian__coord__to__rr__coord__from__source___fake" ],
    [ "clamped_rr_coord_to_pct_coord_Fake", "structclamped__rr__coord__to__pct__coord___fake.html", "structclamped__rr__coord__to__pct__coord___fake" ],
    [ "fff_globals_t", "structfff__globals__t.html", "structfff__globals__t" ],
    [ "field_coord_to_rr_coord_to_target_Fake", "structfield__coord__to__rr__coord__to__target___fake.html", "structfield__coord__to__rr__coord__to__target___fake" ],
    [ "gu_ball_position", "structgu__ball__position.html", "structgu__ball__position" ],
    [ "gu_camera_coordinate_equals_Fake", "structgu__camera__coordinate__equals___fake.html", "structgu__camera__coordinate__equals___fake" ],
    [ "gu_camera_equals_Fake", "structgu__camera__equals___fake.html", "structgu__camera__equals___fake" ],
    [ "gu_camera_pivot_equals_Fake", "structgu__camera__pivot__equals___fake.html", "structgu__camera__pivot__equals___fake" ],
    [ "gu_cartesian_coordinate_equals_Fake", "structgu__cartesian__coordinate__equals___fake.html", "structgu__cartesian__coordinate__equals___fake" ],
    [ "gu_corner_sighting", "structgu__corner__sighting.html", "structgu__corner__sighting" ],
    [ "gu_ellipse_sighting", "structgu__ellipse__sighting.html", "structgu__ellipse__sighting" ],
    [ "gu_field_coordinate_equals_Fake", "structgu__field__coordinate__equals___fake.html", "structgu__field__coordinate__equals___fake" ],
    [ "gu_horizon_sighting", "structgu__horizon__sighting.html", "structgu__horizon__sighting" ],
    [ "gu_line_sighting", "structgu__line__sighting.html", "structgu__line__sighting" ],
    [ "gu_nao", "structgu__nao.html", "structgu__nao" ],
    [ "gu_nao_arm", "structgu__nao__arm.html", "structgu__nao__arm" ],
    [ "gu_nao_hand_sensors", "structgu__nao__hand__sensors.html", "structgu__nao__hand__sensors" ],
    [ "gu_nao_head", "structgu__nao__head.html", "structgu__nao__head" ],
    [ "gu_nao_head_sensors", "structgu__nao__head__sensors.html", "structgu__nao__head__sensors" ],
    [ "gu_nao_joints", "structgu__nao__joints.html", "structgu__nao__joints" ],
    [ "gu_nao_leg", "structgu__nao__leg.html", "structgu__nao__leg" ],
    [ "gu_nao_wb_indexes", "structgu__nao__wb__indexes.html", "structgu__nao__wb__indexes" ],
    [ "gu_nao_wb_types", "structgu__nao__wb__types.html", "structgu__nao__wb__types" ],
    [ "gu_optional_ball_position", "structgu__optional__ball__position.html", "structgu__optional__ball__position" ],
    [ "gu_optional_corner_sighting", "structgu__optional__corner__sighting.html", "structgu__optional__corner__sighting" ],
    [ "gu_optional_ellipse_sighting", "structgu__optional__ellipse__sighting.html", "structgu__optional__ellipse__sighting" ],
    [ "gu_optional_horizon_sighting", "structgu__optional__horizon__sighting.html", "structgu__optional__horizon__sighting" ],
    [ "gu_optional_line_sighting", "structgu__optional__line__sighting.html", "structgu__optional__line__sighting" ],
    [ "gu_optional_rectangle_sighting", "structgu__optional__rectangle__sighting.html", "structgu__optional__rectangle__sighting" ],
    [ "gu_orientation", "structgu__orientation.html", "structgu__orientation" ],
    [ "gu_percent_coordinate_equals_Fake", "structgu__percent__coordinate__equals___fake.html", "structgu__percent__coordinate__equals___fake" ],
    [ "gu_pitch_joint", "structgu__pitch__joint.html", "structgu__pitch__joint" ],
    [ "gu_pitch_roll_joint", "structgu__pitch__roll__joint.html", "structgu__pitch__roll__joint" ],
    [ "gu_pitch_yaw_joint", "structgu__pitch__yaw__joint.html", "structgu__pitch__yaw__joint" ],
    [ "gu_pixel_coordinate_equals_Fake", "structgu__pixel__coordinate__equals___fake.html", "structgu__pixel__coordinate__equals___fake" ],
    [ "gu_rectangle_sighting", "structgu__rectangle__sighting.html", "structgu__rectangle__sighting" ],
    [ "gu_relative_coordinate_equals_Fake", "structgu__relative__coordinate__equals___fake.html", "structgu__relative__coordinate__equals___fake" ],
    [ "gu_soccer_locations", "structgu__soccer__locations.html", "structgu__soccer__locations" ],
    [ "gu_soccer_sightings", "structgu__soccer__sightings.html", "structgu__soccer__sightings" ],
    [ "gu_yaw_joint", "structgu__yaw__joint.html", "structgu__yaw__joint" ],
    [ "gu_yaw_roll_joint", "structgu__yaw__roll__joint.html", "structgu__yaw__roll__joint" ],
    [ "gu_yp_joint", "structgu__yp__joint.html", "structgu__yp__joint" ],
    [ "pct_coord_to_px_coord_Fake", "structpct__coord__to__px__coord___fake.html", "structpct__coord__to__px__coord___fake" ],
    [ "pct_coord_to_rr_coord_Fake", "structpct__coord__to__rr__coord___fake.html", "structpct__coord__to__rr__coord___fake" ],
    [ "px_coord_to_cam_coord_Fake", "structpx__coord__to__cam__coord___fake.html", "structpx__coord__to__cam__coord___fake" ],
    [ "px_coord_to_pct_coord_Fake", "structpx__coord__to__pct__coord___fake.html", "structpx__coord__to__pct__coord___fake" ],
    [ "rr_coord_to_cartesian_coord_Fake", "structrr__coord__to__cartesian__coord___fake.html", "structrr__coord__to__cartesian__coord___fake" ],
    [ "rr_coord_to_cartesian_coord_from_field_Fake", "structrr__coord__to__cartesian__coord__from__field___fake.html", "structrr__coord__to__cartesian__coord__from__field___fake" ],
    [ "rr_coord_to_cartesian_coord_from_source_Fake", "structrr__coord__to__cartesian__coord__from__source___fake.html", "structrr__coord__to__cartesian__coord__from__source___fake" ],
    [ "rr_coord_to_field_coord_Fake", "structrr__coord__to__field__coord___fake.html", "structrr__coord__to__field__coord___fake" ],
    [ "rr_coord_to_field_coord_from_source_Fake", "structrr__coord__to__field__coord__from__source___fake.html", "structrr__coord__to__field__coord__from__source___fake" ],
    [ "rr_coord_to_pct_coord_Fake", "structrr__coord__to__pct__coord___fake.html", "structrr__coord__to__pct__coord___fake" ]
];