gurobots: ball_position.c File Reference
ball_position.c File Reference
#include "ball_position.h"
Functions
bool gu_ball_position_equals (const gu_ball_position lhs, const gu_ball_position rhs, const degrees_f tolerance)
Function Documentation
gu_ball_position_equals()
bool gu_ball_position_equals (const gu_ball_position lhs, const gu_ball_position rhs, const degrees_f tolerance)
Definition at line 61 of file ball_position.c.
References gu_cartesian_coordinate_equals(), gu_orientation_equals(), gu_ball_position::orientation, and gu_ball_position::position.
Referenced by gu_optional_ball_position_equals().