gurobots: CGTEST::NaoV5CPPTests Class Reference
CGTEST::NaoV5CPPTests Class Reference
Protected Member Functions
void postPitch (float pitch)
virtual void SetUp ()
GU::NaoV5 initial ()
GU::NaoV5 empty ()
void change (GU::NaoV5 &obj)
Protected Member Functions inherited from CGTEST::GURobotsTests< GU::NaoV5 >
virtual void TearDown ()
virtual void TearDown ()
bool near (const float lhs, const float rhs) const
bool near (const float lhs, const float rhs) const
void assert_near (const float lhs, const float rhs, const float tolerance) const
void assert_near (const float lhs, const float rhs, const float tolerance) const
void equals (const gu_camera_pivot lhs, const gu_camera_pivot rhs)
void equals (const gu_cartesian_coordinate lhs, const gu_cartesian_coordinate rhs)
void equals (const gu_field_coordinate lhs, const gu_field_coordinate rhs)
void equals (const GU::NaoV5 lhs, const GU::NaoV5 rhs)
void nequals (const gu_camera_pivot lhs, const gu_camera_pivot rhs)
void nequals (const gu_cartesian_coordinate lhs, const gu_cartesian_coordinate rhs)
void nequals (const gu_field_coordinate lhs, const gu_field_coordinate rhs)
void nequals (const GU::NaoV5 lhs, const GU::NaoV5 rhs)
virtual void preamble ()
void ro3_test ()
void ro5_test ()
Protected Attributes
gu_simple_whiteboard * wb
Detailed Description
Definition at line 67 of file NaoV5Tests.cc.
Member Function Documentation
change()
void CGTEST::NaoV5CPPTests::change (GU::NaoV5 & obj) inline protected virtual
Reimplemented from CGTEST::GURobotsTests< GU::NaoV5 >.
Definition at line 102 of file NaoV5Tests.cc.
References postPitch(), and GU::NaoV5::update().
empty()
GU::NaoV5 CGTEST::NaoV5CPPTests::empty () inline protected virtual
Implements CGTEST::GURobotsTests< GU::NaoV5 >.
Definition at line 97 of file NaoV5Tests.cc.
References wb.
initial()
GU::NaoV5 CGTEST::NaoV5CPPTests::initial () inline protected virtual
Implements CGTEST::GURobotsTests< GU::NaoV5 >.
Definition at line 89 of file NaoV5Tests.cc.
References postPitch(), GU::NaoV5::update(), and wb.
postPitch()
void CGTEST::NaoV5CPPTests::postPitch (float pitch) inline protected
Definition at line 73 of file NaoV5Tests.cc.
References wb.
Referenced by change(), and initial().
SetUp()
virtual void CGTEST::NaoV5CPPTests::SetUp () inline protected virtual
Reimplemented from CGTEST::GURobotsTests< GU::NaoV5 >.
Definition at line 82 of file NaoV5Tests.cc.
References CGTEST::GURobotsTests< Class >::SetUp(), and wb.
Member Data Documentation
wb
gu_simple_whiteboard* CGTEST::NaoV5CPPTests::wb protected
Definition at line 71 of file NaoV5Tests.cc.
Referenced by empty(), initial(), postPitch(), and SetUp().
The documentation for this class was generated from the following file:
tests/NaoV5Tests.cc