gurobots: CGTEST::GURobotsTests< Class > Class Template Reference
CGTEST::GURobotsTests< Class > Class Template Reference abstract
#include <gurobots_tests.hpp>
Protected Member Functions
virtual void SetUp ()
virtual void TearDown ()
bool near (const float lhs, const float rhs) const
void assert_near (const float lhs, const float rhs, const float tolerance) const
void equals (const gu_camera_pivot lhs, const gu_camera_pivot rhs)
void nequals (const gu_camera_pivot lhs, const gu_camera_pivot rhs)
void equals (const gu_cartesian_coordinate lhs, const gu_cartesian_coordinate rhs)
void nequals (const gu_cartesian_coordinate lhs, const gu_cartesian_coordinate rhs)
void equals (const gu_field_coordinate lhs, const gu_field_coordinate rhs)
void nequals (const gu_field_coordinate lhs, const gu_field_coordinate rhs)
virtual void SetUp ()
virtual void TearDown ()
virtual void preamble ()
virtual Class initial ()=0
virtual void change (Class &)
virtual Class empty ()=0
void ro3_test ()
void ro5_test ()
bool near (const float lhs, const float rhs) const
void assert_near (const float lhs, const float rhs, const float tolerance) const
void equals (const GU::NaoV5 lhs, const GU::NaoV5 rhs)
void nequals (const GU::NaoV5 lhs, const GU::NaoV5 rhs)
Detailed Description
template<typename Class>
class CGTEST::GURobotsTests< Class >
Definition at line 91 of file gurobots_tests.hpp.
Member Function Documentation
assert_near() [1/2]
template<typename Class > void CGTEST::GURobotsTests< Class >::assert_near (const float lhs, const float rhs, const float tolerance) const inline protected
Definition at line 110 of file gurobots_tests.hpp.
Referenced by CGTEST::GURobotsTests< Class >::equals().
assert_near() [2/2]
template<typename Class > void CGTEST::GURobotsTests< Class >::assert_near (const float lhs, const float rhs, const float tolerance) const inline protected
Definition at line 199 of file GURobotsTests.hpp.
change()
template<typename Class > virtual void CGTEST::GURobotsTests< Class >::change (Class &) inline protected virtual
Reimplemented in CGTEST::NaoV5CPPTests.
Definition at line 144 of file GURobotsTests.hpp.
Referenced by CGTEST::GURobotsTests< Class >::ro3_test().
empty()
template<typename Class > virtual Class CGTEST::GURobotsTests< Class >::empty () protected pure virtual
Implemented in CGTEST::NaoV5CPPTests.
Referenced by CGTEST::GURobotsTests< Class >::ro5_test().
equals() [1/4]
template<typename Class > void CGTEST::GURobotsTests< Class >::equals (const GU::NaoV5 lhs, const GU::NaoV5 rhs) inline protected
Definition at line 209 of file GURobotsTests.hpp.
equals() [2/4]
template<typename Class > void CGTEST::GURobotsTests< Class >::equals (const gu_camera_pivot lhs, const gu_camera_pivot rhs) inline protected
Definition at line 115 of file gurobots_tests.hpp.
References CGTEST::GURobotsTests< Class >::assert_near(), and CGTEST::GURobotsTests< Class >::near().
Referenced by CGTEST::GURobotsTests< Class >::equals(), CGTEST::GURobotsTests< Class >::ro3_test(), and CGTEST::GURobotsTests< Class >::ro5_test().
equals() [3/4]
template<typename Class > void CGTEST::GURobotsTests< Class >::equals (const gu_cartesian_coordinate lhs, const gu_cartesian_coordinate rhs) inline protected
Definition at line 162 of file gurobots_tests.hpp.
equals() [4/4]
template<typename Class > void CGTEST::GURobotsTests< Class >::equals (const gu_field_coordinate lhs, const gu_field_coordinate rhs) inline protected
Definition at line 173 of file gurobots_tests.hpp.
References CGTEST::GURobotsTests< Class >::equals().
initial()
template<typename Class > virtual Class CGTEST::GURobotsTests< Class >::initial () protected pure virtual
Implemented in CGTEST::NaoV5CPPTests.
Referenced by CGTEST::GURobotsTests< Class >::ro3_test(), and CGTEST::GURobotsTests< Class >::ro5_test().
near() [1/2]
template<typename Class > bool CGTEST::GURobotsTests< Class >::near (const float lhs, const float rhs) const inline protected
Definition at line 104 of file gurobots_tests.hpp.
Referenced by CGTEST::GURobotsTests< Class >::equals(), and CGTEST::GURobotsTests< Class >::nequals().
near() [2/2]
template<typename Class > bool CGTEST::GURobotsTests< Class >::near (const float lhs, const float rhs) const inline protected
Definition at line 193 of file GURobotsTests.hpp.
nequals() [1/4]
template<typename Class > void CGTEST::GURobotsTests< Class >::nequals (const GU::NaoV5 lhs, const GU::NaoV5 rhs) inline protected
Definition at line 215 of file GURobotsTests.hpp.
nequals() [2/4]
template<typename Class > void CGTEST::GURobotsTests< Class >::nequals (const gu_camera_pivot lhs, const gu_camera_pivot rhs) inline protected
Definition at line 134 of file gurobots_tests.hpp.
References CGTEST::GURobotsTests< Class >::near().
Referenced by CGTEST::GURobotsTests< Class >::ro3_test(), and CGTEST::GURobotsTests< Class >::ro5_test().
nequals() [3/4]
template<typename Class > void CGTEST::GURobotsTests< Class >::nequals (const gu_cartesian_coordinate lhs, const gu_cartesian_coordinate rhs) inline protected
Definition at line 168 of file gurobots_tests.hpp.
nequals() [4/4]
template<typename Class > void CGTEST::GURobotsTests< Class >::nequals (const gu_field_coordinate lhs, const gu_field_coordinate rhs) inline protected
Definition at line 179 of file gurobots_tests.hpp.
preamble()
template<typename Class > virtual void CGTEST::GURobotsTests< Class >::preamble () inline protected virtual
Definition at line 140 of file GURobotsTests.hpp.
Referenced by CGTEST::GURobotsTests< Class >::ro3_test().
ro3_test()
template<typename Class > void CGTEST::GURobotsTests< Class >::ro3_test () inline protected
Definition at line 148 of file GURobotsTests.hpp.
References CGTEST::GURobotsTests< Class >::change(), CGTEST::GURobotsTests< Class >::equals(), CGTEST::GURobotsTests< Class >::initial(), CGTEST::GURobotsTests< Class >::nequals(), and CGTEST::GURobotsTests< Class >::preamble().
ro5_test()
template<typename Class > void CGTEST::GURobotsTests< Class >::ro5_test () inline protected
Definition at line 171 of file GURobotsTests.hpp.
References CGTEST::GURobotsTests< Class >::empty(), CGTEST::GURobotsTests< Class >::equals(), CGTEST::GURobotsTests< Class >::initial(), and CGTEST::GURobotsTests< Class >::nequals().
SetUp() [1/2]
template<typename Class > virtual void CGTEST::GURobotsTests< Class >::SetUp () inline protected virtual
Reimplemented in CGTEST::NaoV5CPPTests.
Definition at line 94 of file gurobots_tests.hpp.
References ALL_FAKES, FFF_RESET_HISTORY, and RESET_FAKE.
Referenced by CGTEST::NaoV5CPPTests::SetUp().
SetUp() [2/2]
template<typename Class > virtual void CGTEST::GURobotsTests< Class >::SetUp () inline protected virtual
Reimplemented in CGTEST::NaoV5CPPTests.
Definition at line 130 of file GURobotsTests.hpp.
References ALL_FAKES, FFF_RESET_HISTORY, and RESET_FAKE.
TearDown() [1/2]
template<typename Class > virtual void CGTEST::GURobotsTests< Class >::TearDown () inline protected virtual
Definition at line 99 of file gurobots_tests.hpp.
References ALL_FAKES, FFF_RESET_HISTORY, and RESET_FAKE.
TearDown() [2/2]
template<typename Class > virtual void CGTEST::GURobotsTests< Class >::TearDown () inline protected virtual
Definition at line 135 of file GURobotsTests.hpp.
References ALL_FAKES, FFF_RESET_HISTORY, and RESET_FAKE.
The documentation for this class was generated from the following files:
ctests/gurobots_tests.hpp
tests/GURobotsTests.hpp