gurobots: horizon_sighting.c File Reference
horizon_sighting.c File Reference
#include "horizon_sighting.h"
Functions
bool gu_horizon_sighting_equals (const gu_horizon_sighting lhs, const gu_horizon_sighting rhs)
gu_horizon_sighting wb_vision_detection_horizon_to_horizon_sighting (const struct wb_vision_detection_horizon horizon, const uint16_t resWidth, const uint16_t resHeight)
Function Documentation
gu_horizon_sighting_equals()
bool gu_horizon_sighting_equals (const gu_horizon_sighting lhs, const gu_horizon_sighting rhs)
Definition at line 61 of file horizon_sighting.c.
References gu_horizon_sighting::cornerSighting, gu_corner_sighting_equals(), gu_line_sighting_equals(), GUHorizonSightingField, GUHorizonSightingLine, gu_horizon_sighting::lineSighting, and gu_horizon_sighting::sightingType.
Referenced by gu_optional_horizon_sighting_equals().
wb_vision_detection_horizon_to_horizon_sighting()
gu_horizon_sighting wb_vision_detection_horizon_to_horizon_sighting (const struct wb_vision_detection_horizon horizon, const uint16_t resWidth, const uint16_t resHeight)
Definition at line 69 of file horizon_sighting.c.
References GUHorizonSightingCorner, GUHorizonSightingField, GUHorizonSightingLine, and gu_horizon_sighting::sightingType.
Referenced by wb_vision_detection_horizon_to_opt_horizon_sighting().