gurobots: nao.h File Reference
nao.h File Reference
#include <guunits/guunits.h>
#include <gucoordinates/gucoordinates.h>
#include <stdbool.h>
#include <gusimplewhiteboard/gusimplewhiteboard.h>
#include <gusimplewhiteboard/guwhiteboardtypelist_c_generated.h>
#include <gusimplewhiteboard/typeClassDefs/wb_sensors_torsojointsensors.h>
#include <gusimplewhiteboard/typeClassDefs/wb_top_particles.h>
#include <gusimplewhiteboard/typeClassDefs/wb_ball_position.h>
#include <gusimplewhiteboard/typeClassDefs/wb_sensors_head_sensors.h>
#include <gusimplewhiteboard/typeClassDefs/wb_sensors_hand_sensors.h>
#include <gusimplewhiteboard/typeClassDefs/wb_sensors_legjointsensors.h>
#include <gusimplewhiteboard/typeClassDefs/wb_location.h>
#include <gusimplewhiteboard/typeClassDefs/wb_vision_detection_balls.h>
#include <gusimplewhiteboard/typeClassDefs/wb_vision_detection_goals.h>
#include <gusimplewhiteboard/typeClassDefs/wb_vision_detection_horizons.h>
#include <gusimplewhiteboard/typeClassDefs/wb_vision_lines.h>
#include <gusimplewhiteboard/typeClassDefs/wb_vision_field_features.h>
#include "pitch_joint.h"
#include "pitch_roll_joint.h"
#include "pitch_yaw_joint.h"
#include "yaw_roll_joint.h"
#include "yaw_joint.h"
#include "yp_joint.h"
#include "soccer_locations.h"
#include "soccer_sightings.h"
#include "optional_ball_position.h"
Classes
struct gu_nao_head_sensors
struct gu_nao_head
struct gu_nao_hand_sensors
struct gu_nao_arm
struct gu_nao_leg
struct gu_nao_joints
struct gu_nao
struct gu_nao_wb_indexes
struct gu_nao_wb_types
Macros
#define GU_NAO_V5_TOP_CAMERA_INDEX 0
#define GU_NAO_V5_BOTTOM_CAMERA_INDEX 1
Typedefs
typedef struct gu_nao_head_sensors gu_nao_head_sensors
typedef struct gu_nao_head gu_nao_head
typedef struct gu_nao_hand_sensors gu_nao_hand_sensors
typedef struct gu_nao_arm gu_nao_arm
typedef struct gu_nao_leg gu_nao_leg
typedef struct gu_nao_joints gu_nao_joints
typedef struct gu_nao gu_nao
typedef struct gu_nao_wb_indexes gu_nao_wb_indexes
typedef struct gu_nao_wb_types gu_nao_wb_types
Functions
bool gu_nao_head_sensors_equals (const gu_nao_head_sensors, const gu_nao_head_sensors)
bool gu_nao_head_equals (const gu_nao_head lhs, const gu_nao_head rhs)
gu_camera_pivot gu_nao_head_to_camera_pivot (const gu_nao_head)
bool gu_nao_hand_sensors_equals (const gu_nao_hand_sensors, const gu_nao_hand_sensors)
bool gu_nao_arm_equals (const gu_nao_arm lhs, const gu_nao_arm rhs)
bool gu_nao_leg_equals (const gu_nao_leg lhs, const gu_nao_leg rhs)
bool gu_nao_joints_equals (const gu_nao_joints lhs, const gu_nao_joints rhs)
bool gu_nao_equals (const gu_nao lhs, const gu_nao rhs)
void gu_nao_empty (gu_nao *)
bool gu_nao_wb_indexes_equals (const gu_nao_wb_indexes lhs, const gu_nao_wb_indexes rhs) __attribute__((const))
gu_nao_wb_indexes gu_nao_wb_indexes_default (void) __attribute__((const))
gu_nao_wb_types gu_nao_wb_types_from_wb (gu_simple_whiteboard *) __attribute__((nonnull))
gu_nao_wb_types gu_nao_wb_types_from_custom_wb (gu_simple_whiteboard *, const gu_nao_wb_indexes) __attribute__((nonnull))
void gu_nao_update_from_wb (gu_nao *, gu_simple_whiteboard *) __attribute__((nonnull))
void gu_nao_update_from_custom_wb (gu_nao *, gu_simple_whiteboard *, const gu_nao_wb_indexes) __attribute__((nonnull))
void gu_nao_update_from_wb_types (gu_nao *, const gu_nao_wb_types) __attribute__((nonnull))
Macro Definition Documentation
GU_NAO_V5_BOTTOM_CAMERA_INDEX
#define GU_NAO_V5_BOTTOM_CAMERA_INDEX 1
Definition at line 96 of file nao.h.
GU_NAO_V5_TOP_CAMERA_INDEX
#define GU_NAO_V5_TOP_CAMERA_INDEX 0
Definition at line 95 of file nao.h.
Typedef Documentation
gu_nao
typedef struct gu_nao gu_nao
gu_nao_arm
typedef struct gu_nao_arm gu_nao_arm
gu_nao_hand_sensors
typedef struct gu_nao_hand_sensors gu_nao_hand_sensors
gu_nao_head
typedef struct gu_nao_head gu_nao_head
gu_nao_head_sensors
typedef struct gu_nao_head_sensors gu_nao_head_sensors
gu_nao_joints
typedef struct gu_nao_joints gu_nao_joints
gu_nao_leg
typedef struct gu_nao_leg gu_nao_leg
gu_nao_wb_indexes
typedef struct gu_nao_wb_indexes gu_nao_wb_indexes
gu_nao_wb_types
typedef struct gu_nao_wb_types gu_nao_wb_types
Function Documentation
gu_nao_arm_equals()
bool gu_nao_arm_equals (const gu_nao_arm lhs, const gu_nao_arm rhs)
Definition at line 95 of file nao.c.
References gu_nao_arm::elbow, gu_nao_hand_sensors_equals(), gu_pitch_roll_joint_equals(), gu_yaw_joint_equals(), gu_yaw_roll_joint_equals(), gu_nao_arm::hand, gu_nao_arm::shoulder, and gu_nao_arm::wrist.
Referenced by gu_nao_joints_equals().
gu_nao_empty()
void gu_nao_empty (gu_nao * nao)
Definition at line 296 of file nao.c.
References gu_nao_joints::head, gu_nao::joints, gu_nao_head::neck, and gu_pitch_yaw_joint::pitch.
Referenced by GU::NaoV5::NaoV5(), and GU::NaoV5::operator=().
gu_nao_equals()
bool gu_nao_equals (const gu_nao lhs, const gu_nao rhs)
Definition at line 119 of file nao.c.
References gu_nao::ballPosition, gu_nao::fieldPosition, gu_nao_joints_equals(), gu_optional_ball_position_equals(), gu_soccer_locations_equals(), gu_nao::joints, gu_nao::locations, and gu_nao::playerNumber.
gu_nao_hand_sensors_equals()
bool gu_nao_hand_sensors_equals (const gu_nao_hand_sensors, const gu_nao_hand_sensors)
Definition at line 88 of file nao.c.
References gu_nao_hand_sensors::touchBack, gu_nao_hand_sensors::touchLeft, and gu_nao_hand_sensors::touchRight.
Referenced by gu_nao_arm_equals().
gu_nao_head_equals()
bool gu_nao_head_equals (const gu_nao_head lhs, const gu_nao_head rhs)
Definition at line 76 of file nao.c.
References gu_nao_head::buttons, gu_nao_head_sensors_equals(), gu_pitch_yaw_joint_equals(), and gu_nao_head::neck.
Referenced by gu_nao_joints_equals().
gu_nao_head_sensors_equals()
bool gu_nao_head_sensors_equals (const gu_nao_head_sensors, const gu_nao_head_sensors)
Definition at line 69 of file nao.c.
References gu_nao_head_sensors::touchFront, gu_nao_head_sensors::touchMiddle, and gu_nao_head_sensors::touchRear.
Referenced by gu_nao_head_equals().
gu_nao_head_to_camera_pivot()
gu_camera_pivot gu_nao_head_to_camera_pivot (const gu_nao_head)
Definition at line 82 of file nao.c.
References GU_NAO_V5_HEAD, gu_nao_head::neck, gu_pitch_yaw_joint::pitch, and gu_pitch_yaw_joint::yaw.
Referenced by GU::NaoV5::cameraPivot().
gu_nao_joints_equals()
bool gu_nao_joints_equals (const gu_nao_joints lhs, const gu_nao_joints rhs)
Definition at line 110 of file nao.c.
References gu_nao_arm_equals(), gu_nao_head_equals(), gu_nao_leg_equals(), gu_nao_joints::head, gu_nao_joints::leftArm, gu_nao_joints::leftLeg, gu_nao_joints::rightArm, and gu_nao_joints::rightLeg.
Referenced by gu_nao_equals().
gu_nao_leg_equals()
bool gu_nao_leg_equals (const gu_nao_leg lhs, const gu_nao_leg rhs)
Definition at line 103 of file nao.c.
References gu_nao_leg::ankle, gu_pitch_joint_equals(), gu_pitch_roll_joint_equals(), gu_yp_joint_equals(), gu_nao_leg::hip, and gu_nao_leg::knee.
Referenced by gu_nao_joints_equals().
gu_nao_update_from_custom_wb()
void gu_nao_update_from_custom_wb (gu_nao * nao, gu_simple_whiteboard * wb, const gu_nao_wb_indexes)
Definition at line 220 of file nao.c.
References gu_nao_update_from_wb_types(), and gu_nao_wb_types_from_custom_wb().
Referenced by gu_nao_update_from_wb().
gu_nao_update_from_wb()
void gu_nao_update_from_wb (gu_nao * nao, gu_simple_whiteboard * wb)
Definition at line 214 of file nao.c.
References gu_nao_update_from_custom_wb(), and gu_nao_wb_indexes_default().
Referenced by GU::NaoV5::update().
gu_nao_update_from_wb_types()
void gu_nao_update_from_wb_types (gu_nao * nao, const gu_nao_wb_types)
Definition at line 226 of file nao.c.
References gu_nao_leg::ankle, gu_soccer_locations::ball, gu_soccer_sightings::ball, gu_nao_wb_types::ballLocation, gu_nao::ballPosition, gu_nao_wb_types::ballPosition, gu_nao_wb_types::ballSightings, gu_nao::bottomCameraSightings, gu_nao_wb_types::bottomLineSightings, gu_nao_head::buttons, gu_nao_arm::elbow, gu_nao::fieldPosition, gu_soccer_locations::goal, gu_nao_wb_types::goalLocation, gu_nao_wb_types::goalSightings, gu_soccer_sightings_update_from_wb_vision_detection_goal(), gu_soccer_sightings_update_from_wb_vision_line_array(), gu_nao_arm::hand, gu_nao_wb_types::handSensors, gu_optional_ball_position::has_value, gu_nao_joints::head, gu_nao_wb_types::headSensors, gu_nao_leg::hip, gu_soccer_sightings::horizon, gu_nao_wb_types::horizonSightings, gu_nao::joints, gu_nao_leg::knee, gu_nao_joints::leftArm, gu_soccer_locations::leftGoalPost, gu_nao_wb_types::leftGoalPostLocation, gu_nao_joints::leftLeg, gu_nao_wb_types::legSensors, gu_nao::locations, gu_nao_head::neck, gu_ball_position::orientation, gu_orientation::pitch, gu_pitch_joint::pitch, gu_pitch_roll_joint::pitch, gu_pitch_yaw_joint::pitch, gu_yp_joint::pitch, gu_nao::playerNumber, gu_nao_wb_types::playerNumber, gu_ball_position::position, gu_nao_joints::rightArm, gu_soccer_locations::rightGoalPost, gu_nao_wb_types::rightGoalPostLocation, gu_nao_joints::rightLeg, gu_orientation::roll, gu_pitch_roll_joint::roll, gu_yaw_roll_joint::roll, gu_yp_joint::roll, gu_nao_arm::shoulder, gu_nao::topCameraSightings, gu_nao_wb_types::topLineSightings, gu_nao_wb_types::topParticles, gu_nao_wb_types::torsoSensors, gu_nao_hand_sensors::touchBack, gu_nao_head_sensors::touchFront, gu_nao_hand_sensors::touchLeft, gu_nao_head_sensors::touchMiddle, gu_nao_head_sensors::touchRear, gu_nao_hand_sensors::touchRight, gu_optional_ball_position::value, wb_vision_detection_ball_to_opt_ellipse_sighting(), wb_vision_detection_horizon_to_opt_horizon_sighting(), gu_nao_arm::wrist, gu_orientation::yaw, gu_pitch_yaw_joint::yaw, gu_yaw_joint::yaw, gu_yaw_roll_joint::yaw, and gu_yp_joint::yawPitch.
Referenced by gu_nao_update_from_custom_wb().
gu_nao_wb_indexes_default()
gu_nao_wb_indexes gu_nao_wb_indexes_default (void) const
gu_nao_wb_indexes_equals()
bool gu_nao_wb_indexes_equals (const gu_nao_wb_indexes lhs, const gu_nao_wb_indexes rhs) const
gu_nao_wb_types_from_custom_wb()
gu_nao_wb_types gu_nao_wb_types_from_custom_wb (gu_simple_whiteboard * wb, const gu_nao_wb_indexes)
Definition at line 173 of file nao.c.
References gu_nao_wb_indexes::ballLocation, gu_nao_wb_indexes::ballPosition, gu_nao_wb_indexes::ballSightings, gu_nao_wb_indexes::bottomLineSightings, gu_nao_wb_indexes::fieldFeatureSightings, gu_nao_wb_indexes::goalLocation, gu_nao_wb_indexes::goalSightings, gu_nao_wb_indexes::handSensors, gu_nao_wb_indexes::headSensors, gu_nao_wb_indexes::horizonSightings, gu_nao_wb_indexes::leftGoalPostLocation, gu_nao_wb_indexes::legSensors, gu_nao_wb_indexes::playerNumber, gu_nao_wb_indexes::rightGoalPostLocation, gu_nao_wb_indexes::topLineSightings, gu_nao_wb_indexes::topParticles, and gu_nao_wb_indexes::torsoSensors.
Referenced by gu_nao_update_from_custom_wb(), and gu_nao_wb_types_from_wb().
gu_nao_wb_types_from_wb()
gu_nao_wb_types gu_nao_wb_types_from_wb (gu_simple_whiteboard * wb)
Definition at line 167 of file nao.c.
References gu_nao_wb_indexes_default(), and gu_nao_wb_types_from_custom_wb().