gurobots: nao.c File Reference
nao.c File Reference
#include "nao.h"
#include <guunits/guunits.h>
#include <gusimplewhiteboard/typeClassDefs/wb_vision_control_status.h>
Macros
#define GU_NAO_V5_TOP_CAMERA gu_camera_make(6.364, 5.871, 1.2, 47.64, 60.97)
#define GU_NAO_V5_BOTTOM_CAMERA gu_camera_make(1.774, 5.071, 39.7, 47.64, 60.97)
#define GU_NAO_V5_HEAD(p, y) (gu_camera_pivot) { .pitch = p, .yaw = y, .height = 41.7, .cameras = {GU_NAO_V5_TOP_CAMERA, GU_NAO_V5_BOTTOM_CAMERA}, .numCameras = 2}
Functions
bool gu_nao_head_sensors_equals (const gu_nao_head_sensors lhs, const gu_nao_head_sensors rhs)
bool gu_nao_head_equals (const gu_nao_head lhs, const gu_nao_head rhs)
gu_camera_pivot gu_nao_head_to_camera_pivot (const gu_nao_head head)
bool gu_nao_hand_sensors_equals (const gu_nao_hand_sensors lhs, const gu_nao_hand_sensors rhs)
bool gu_nao_arm_equals (const gu_nao_arm lhs, const gu_nao_arm rhs)
bool gu_nao_leg_equals (const gu_nao_leg lhs, const gu_nao_leg rhs)
bool gu_nao_joints_equals (const gu_nao_joints lhs, const gu_nao_joints rhs)
bool gu_nao_equals (const gu_nao lhs, const gu_nao rhs)
bool gu_nao_wb_indexes_equals (const gu_nao_wb_indexes lhs, const gu_nao_wb_indexes rhs)
gu_nao_wb_indexes gu_nao_wb_indexes_default ()
gu_nao_wb_types gu_nao_wb_types_from_wb (gu_simple_whiteboard *wb)
gu_nao_wb_types gu_nao_wb_types_from_custom_wb (gu_simple_whiteboard *wb, const gu_nao_wb_indexes indexes)
void gu_nao_update_from_wb (gu_nao *nao, gu_simple_whiteboard *wb)
void gu_nao_update_from_custom_wb (gu_nao *nao, gu_simple_whiteboard *wb, const gu_nao_wb_indexes indexes)
void gu_nao_update_from_wb_types (gu_nao *nao, const gu_nao_wb_types types)
void gu_nao_empty (gu_nao *nao)
Macro Definition Documentation
GU_NAO_V5_BOTTOM_CAMERA
#define GU_NAO_V5_BOTTOM_CAMERA gu_camera_make(1.774, 5.071, 39.7, 47.64, 60.97)
Definition at line 65 of file nao.c.
GU_NAO_V5_HEAD
#define GU_NAO_V5_HEAD (p, y) (gu_camera_pivot) { .pitch = p, .yaw = y, .height = 41.7, .cameras = {GU_NAO_V5_TOP_CAMERA, GU_NAO_V5_BOTTOM_CAMERA}, .numCameras = 2}
Definition at line 67 of file nao.c.
GU_NAO_V5_TOP_CAMERA
#define GU_NAO_V5_TOP_CAMERA gu_camera_make(6.364, 5.871, 1.2, 47.64, 60.97)
Definition at line 64 of file nao.c.
Function Documentation
gu_nao_arm_equals()
bool gu_nao_arm_equals (const gu_nao_arm lhs, const gu_nao_arm rhs)
Definition at line 95 of file nao.c.
References gu_nao_arm::elbow, gu_nao_hand_sensors_equals(), gu_pitch_roll_joint_equals(), gu_yaw_joint_equals(), gu_yaw_roll_joint_equals(), gu_nao_arm::hand, gu_nao_arm::shoulder, and gu_nao_arm::wrist.
Referenced by gu_nao_joints_equals().
gu_nao_empty()
void gu_nao_empty (gu_nao * nao)
Definition at line 296 of file nao.c.
References gu_nao_joints::head, gu_nao::joints, gu_nao_head::neck, and gu_pitch_yaw_joint::pitch.
Referenced by GU::NaoV5::NaoV5(), and GU::NaoV5::operator=().
gu_nao_equals()
bool gu_nao_equals (const gu_nao lhs, const gu_nao rhs)
Definition at line 119 of file nao.c.
References gu_nao::ballPosition, gu_nao::fieldPosition, gu_nao_joints_equals(), gu_optional_ball_position_equals(), gu_soccer_locations_equals(), gu_nao::joints, gu_nao::locations, and gu_nao::playerNumber.
gu_nao_hand_sensors_equals()
bool gu_nao_hand_sensors_equals (const gu_nao_hand_sensors lhs, const gu_nao_hand_sensors rhs)
Definition at line 88 of file nao.c.
References gu_nao_hand_sensors::touchBack, gu_nao_hand_sensors::touchLeft, and gu_nao_hand_sensors::touchRight.
Referenced by gu_nao_arm_equals().
gu_nao_head_equals()
bool gu_nao_head_equals (const gu_nao_head lhs, const gu_nao_head rhs)
Definition at line 76 of file nao.c.
References gu_nao_head::buttons, gu_nao_head_sensors_equals(), gu_pitch_yaw_joint_equals(), and gu_nao_head::neck.
Referenced by gu_nao_joints_equals().
gu_nao_head_sensors_equals()
bool gu_nao_head_sensors_equals (const gu_nao_head_sensors lhs, const gu_nao_head_sensors rhs)
Definition at line 69 of file nao.c.
References gu_nao_head_sensors::touchFront, gu_nao_head_sensors::touchMiddle, and gu_nao_head_sensors::touchRear.
Referenced by gu_nao_head_equals().
gu_nao_head_to_camera_pivot()
gu_camera_pivot gu_nao_head_to_camera_pivot (const gu_nao_head head)
Definition at line 82 of file nao.c.
References GU_NAO_V5_HEAD, gu_nao_head::neck, gu_pitch_yaw_joint::pitch, and gu_pitch_yaw_joint::yaw.
Referenced by GU::NaoV5::cameraPivot().
gu_nao_joints_equals()
bool gu_nao_joints_equals (const gu_nao_joints lhs, const gu_nao_joints rhs)
Definition at line 110 of file nao.c.
References gu_nao_arm_equals(), gu_nao_head_equals(), gu_nao_leg_equals(), gu_nao_joints::head, gu_nao_joints::leftArm, gu_nao_joints::leftLeg, gu_nao_joints::rightArm, and gu_nao_joints::rightLeg.
Referenced by gu_nao_equals().
gu_nao_leg_equals()
bool gu_nao_leg_equals (const gu_nao_leg lhs, const gu_nao_leg rhs)
Definition at line 103 of file nao.c.
References gu_nao_leg::ankle, gu_pitch_joint_equals(), gu_pitch_roll_joint_equals(), gu_yp_joint_equals(), gu_nao_leg::hip, and gu_nao_leg::knee.
Referenced by gu_nao_joints_equals().
gu_nao_update_from_custom_wb()
void gu_nao_update_from_custom_wb (gu_nao * nao, gu_simple_whiteboard * wb, const gu_nao_wb_indexes indexes)
Definition at line 220 of file nao.c.
References gu_nao_update_from_wb_types(), and gu_nao_wb_types_from_custom_wb().
Referenced by gu_nao_update_from_wb().
gu_nao_update_from_wb()
void gu_nao_update_from_wb (gu_nao * nao, gu_simple_whiteboard * wb)
Definition at line 214 of file nao.c.
References gu_nao_update_from_custom_wb(), and gu_nao_wb_indexes_default().
Referenced by GU::NaoV5::update().
gu_nao_update_from_wb_types()
void gu_nao_update_from_wb_types (gu_nao * nao, const gu_nao_wb_types types)
Definition at line 226 of file nao.c.
References gu_nao_leg::ankle, gu_soccer_locations::ball, gu_soccer_sightings::ball, gu_nao_wb_types::ballLocation, gu_nao::ballPosition, gu_nao_wb_types::ballPosition, gu_nao_wb_types::ballSightings, gu_nao::bottomCameraSightings, gu_nao_wb_types::bottomLineSightings, gu_nao_head::buttons, gu_nao_arm::elbow, gu_nao::fieldPosition, gu_soccer_locations::goal, gu_nao_wb_types::goalLocation, gu_nao_wb_types::goalSightings, gu_soccer_sightings_update_from_wb_vision_detection_goal(), gu_soccer_sightings_update_from_wb_vision_line_array(), gu_nao_arm::hand, gu_nao_wb_types::handSensors, gu_optional_ball_position::has_value, gu_nao_joints::head, gu_nao_wb_types::headSensors, gu_nao_leg::hip, gu_soccer_sightings::horizon, gu_nao_wb_types::horizonSightings, gu_nao::joints, gu_nao_leg::knee, gu_nao_joints::leftArm, gu_soccer_locations::leftGoalPost, gu_nao_wb_types::leftGoalPostLocation, gu_nao_joints::leftLeg, gu_nao_wb_types::legSensors, gu_nao::locations, gu_nao_head::neck, gu_ball_position::orientation, gu_orientation::pitch, gu_pitch_joint::pitch, gu_pitch_roll_joint::pitch, gu_pitch_yaw_joint::pitch, gu_yp_joint::pitch, gu_nao::playerNumber, gu_nao_wb_types::playerNumber, gu_ball_position::position, gu_nao_joints::rightArm, gu_soccer_locations::rightGoalPost, gu_nao_wb_types::rightGoalPostLocation, gu_nao_joints::rightLeg, gu_orientation::roll, gu_pitch_roll_joint::roll, gu_yaw_roll_joint::roll, gu_yp_joint::roll, gu_nao_arm::shoulder, gu_nao::topCameraSightings, gu_nao_wb_types::topLineSightings, gu_nao_wb_types::topParticles, gu_nao_wb_types::torsoSensors, gu_nao_hand_sensors::touchBack, gu_nao_head_sensors::touchFront, gu_nao_hand_sensors::touchLeft, gu_nao_head_sensors::touchMiddle, gu_nao_head_sensors::touchRear, gu_nao_hand_sensors::touchRight, gu_optional_ball_position::value, wb_vision_detection_ball_to_opt_ellipse_sighting(), wb_vision_detection_horizon_to_opt_horizon_sighting(), gu_nao_arm::wrist, gu_orientation::yaw, gu_pitch_yaw_joint::yaw, gu_yaw_joint::yaw, gu_yaw_roll_joint::yaw, and gu_yp_joint::yawPitch.
Referenced by gu_nao_update_from_custom_wb().
gu_nao_wb_indexes_default()
gu_nao_wb_indexes gu_nao_wb_indexes_default (void)
Definition at line 143 of file nao.c.
Referenced by gu_nao_update_from_wb(), and gu_nao_wb_types_from_wb().
gu_nao_wb_indexes_equals()
bool gu_nao_wb_indexes_equals (const gu_nao_wb_indexes lhs, const gu_nao_wb_indexes rhs)
Definition at line 128 of file nao.c.
References gu_nao_wb_indexes::ballLocation, gu_nao_wb_indexes::ballPosition, gu_nao_wb_indexes::goalLocation, gu_nao_wb_indexes::handSensors, gu_nao_wb_indexes::headSensors, gu_nao_wb_indexes::leftGoalPostLocation, gu_nao_wb_indexes::legSensors, gu_nao_wb_indexes::playerNumber, gu_nao_wb_indexes::rightGoalPostLocation, gu_nao_wb_indexes::topParticles, and gu_nao_wb_indexes::torsoSensors.
gu_nao_wb_types_from_custom_wb()
gu_nao_wb_types gu_nao_wb_types_from_custom_wb (gu_simple_whiteboard * wb, const gu_nao_wb_indexes indexes)
Definition at line 173 of file nao.c.
References gu_nao_wb_indexes::ballLocation, gu_nao_wb_indexes::ballPosition, gu_nao_wb_indexes::ballSightings, gu_nao_wb_indexes::bottomLineSightings, gu_nao_wb_indexes::fieldFeatureSightings, gu_nao_wb_indexes::goalLocation, gu_nao_wb_indexes::goalSightings, gu_nao_wb_indexes::handSensors, gu_nao_wb_indexes::headSensors, gu_nao_wb_indexes::horizonSightings, gu_nao_wb_indexes::leftGoalPostLocation, gu_nao_wb_indexes::legSensors, gu_nao_wb_indexes::playerNumber, gu_nao_wb_indexes::rightGoalPostLocation, gu_nao_wb_indexes::topLineSightings, gu_nao_wb_indexes::topParticles, and gu_nao_wb_indexes::torsoSensors.
Referenced by gu_nao_update_from_custom_wb(), and gu_nao_wb_types_from_wb().
gu_nao_wb_types_from_wb()
gu_nao_wb_types gu_nao_wb_types_from_wb (gu_simple_whiteboard * wb)
Definition at line 167 of file nao.c.
References gu_nao_wb_indexes_default(), and gu_nao_wb_types_from_custom_wb().