gurobots: ctests/pixel_coordinate_fakes.h File Reference
pixel_coordinate_fakes.h File Reference
#include "fff.h"
#include <gucoordinates/pixel_coordinate.h>
Classes
struct gu_pixel_coordinate_equals_Fake
Macros
#define PIXEL_COORDINATE_FAKES(FAKE) FAKE(gu_pixel_coordinate_equals)
Typedefs
typedef struct gu_pixel_coordinate_equals_Fake gu_pixel_coordinate_equals_Fake
Functions
void gu_pixel_coordinate_equals_reset (void)
bool gu_pixel_coordinate_equals (const gu_pixel_coordinate arg0, const gu_pixel_coordinate arg1)
Variables
gu_pixel_coordinate_equals_Fake gu_pixel_coordinate_equals_fake
Macro Definition Documentation
PIXEL_COORDINATE_FAKES
#define PIXEL_COORDINATE_FAKES (FAKE) FAKE(gu_pixel_coordinate_equals)
Definition at line 69 of file pixel_coordinate_fakes.h.
Typedef Documentation
gu_pixel_coordinate_equals_Fake
typedef struct gu_pixel_coordinate_equals_Fake gu_pixel_coordinate_equals_Fake
Function Documentation
gu_pixel_coordinate_equals()
bool gu_pixel_coordinate_equals (const gu_pixel_coordinate arg0, const gu_pixel_coordinate arg1)
Definition at line 63 of file pixel_coordinate_fakes.c.
Referenced by gu_corner_sighting_equals(), gu_ellipse_sighting_equals(), gu_line_sighting_equals(), gu_rectangle_sighting_equals(), and gu_soccer_sightings_equals().
gu_pixel_coordinate_equals_reset()
void gu_pixel_coordinate_equals_reset (void)
Definition at line 63 of file pixel_coordinate_fakes.c.
Variable Documentation
gu_pixel_coordinate_equals_fake
gu_pixel_coordinate_equals_Fake gu_pixel_coordinate_equals_fake extern
Definition at line 63 of file pixel_coordinate_fakes.c.