gurobots: ctests/pixel_coordinate_fakes.c File Reference
pixel_coordinate_fakes.c File Reference
#include "pixel_coordinate_fakes.h"
Functions
bool gu_pixel_coordinate_equals (const gu_pixel_coordinate arg0, const gu_pixel_coordinate arg1)
void gu_pixel_coordinate_equals_reset (void)
Variables
gu_pixel_coordinate_equals_Fake gu_pixel_coordinate_equals_fake
Function Documentation
gu_pixel_coordinate_equals()
bool gu_pixel_coordinate_equals (const gu_pixel_coordinate arg0, const gu_pixel_coordinate arg1)
Definition at line 63 of file pixel_coordinate_fakes.c.
Referenced by gu_corner_sighting_equals(), gu_ellipse_sighting_equals(), gu_line_sighting_equals(), gu_rectangle_sighting_equals(), and gu_soccer_sightings_equals().
gu_pixel_coordinate_equals_reset()
void gu_pixel_coordinate_equals_reset (void)
Definition at line 63 of file pixel_coordinate_fakes.c.
Variable Documentation
gu_pixel_coordinate_equals_fake
gu_pixel_coordinate_equals_Fake gu_pixel_coordinate_equals_fake
Definition at line 63 of file pixel_coordinate_fakes.c.