gurobots: rectangle_sighting.h File Reference
rectangle_sighting.h File Reference
#include <guunits/guunits.h>
#include <gucoordinates/gucoordinates.h>
#include <gusimplewhiteboard/typeClassDefs/wb_vision_line.h>
Classes
struct gu_rectangle_sighting
Typedefs
typedef struct gu_rectangle_sighting gu_rectangle_sighting
Functions
bool gu_rectangle_sighting_equals (const gu_rectangle_sighting lhs, const gu_rectangle_sighting rhs)
gu_rectangle_sighting wb_vision_line_to_rectangle_sighting (const struct wb_vision_line sighting, const uint16_t resWidth, const uint16_t resHeight) __attribute__((const))
Typedef Documentation
gu_rectangle_sighting
typedef struct gu_rectangle_sighting gu_rectangle_sighting
Function Documentation
gu_rectangle_sighting_equals()
bool gu_rectangle_sighting_equals (const gu_rectangle_sighting lhs, const gu_rectangle_sighting rhs)
Definition at line 61 of file rectangle_sighting.c.
References gu_rectangle_sighting::bottomLeftPoint, gu_rectangle_sighting::bottomRightPoint, gu_pixel_coordinate_equals(), gu_rectangle_sighting::topLeftPoint, and gu_rectangle_sighting::topRightPoint.
Referenced by gu_optional_rectangle_sighting_equals(), and gu_soccer_sightings_equals().
wb_vision_line_to_rectangle_sighting()
gu_rectangle_sighting wb_vision_line_to_rectangle_sighting (const struct wb_vision_line sighting, const uint16_t resWidth, const uint16_t resHeight) const