gurobots: soccer_sightings.h File Reference
soccer_sightings.h File Reference
#include <stdint.h>
#include <gucoordinates/gucoordinates.h>
#include "optional_ellipse_sighting.h"
#include "optional_rectangle_sighting.h"
#include "optional_horizon_sighting.h"
#include "optional_line_sighting.h"
#include <gusimplewhiteboard/typeClassDefs/wb_vision_detection_goal.h>
#include <gusimplewhiteboard/typeClassDefs/wb_vision_line.h>
Classes
struct gu_soccer_sightings
Macros
#define GUROBOTS_SOCCER_SIGHTINGS_MAX_LINE_SIGHTINGS 7
#define GUROBOTS_SOCCER_SIGHTINGS_MAX_LINE_CORNER_SIGHTINGS 8
#define GUROBOTS_SOCCER_SIGHTINGS_MAX_LINE_T_INTERSECTION_SIGHTINGS 8
#define GUROBOTS_SOCCER_SIGHTINGS_MAX_LINE_CROSS_SIGHTINGS 3
Typedefs
typedef struct gu_soccer_sightings gu_soccer_sightings
Functions
bool gu_soccer_sightings_equals (const gu_soccer_sightings lhs, const gu_soccer_sightings rhs)
void gu_soccer_sightings_update_from_wb_vision_detection_goal (gu_soccer_sightings *sightings, const struct wb_vision_detection_goal, const uint16_t resWidth, const uint16_t resHeight) __attribute__((nonnull))
void gu_soccer_sightings_update_from_wb_vision_line_array (gu_soccer_sightings *sightings, const struct wb_vision_line *lines, const int numLines, const uint16_t resWidth, const uint16_t resHeight) __attribute__((nonnull))
Macro Definition Documentation
GUROBOTS_SOCCER_SIGHTINGS_MAX_LINE_CORNER_SIGHTINGS
#define GUROBOTS_SOCCER_SIGHTINGS_MAX_LINE_CORNER_SIGHTINGS 8
Definition at line 75 of file soccer_sightings.h.
GUROBOTS_SOCCER_SIGHTINGS_MAX_LINE_CROSS_SIGHTINGS
#define GUROBOTS_SOCCER_SIGHTINGS_MAX_LINE_CROSS_SIGHTINGS 3
Definition at line 77 of file soccer_sightings.h.
GUROBOTS_SOCCER_SIGHTINGS_MAX_LINE_SIGHTINGS
#define GUROBOTS_SOCCER_SIGHTINGS_MAX_LINE_SIGHTINGS 7
Definition at line 74 of file soccer_sightings.h.
GUROBOTS_SOCCER_SIGHTINGS_MAX_LINE_T_INTERSECTION_SIGHTINGS
#define GUROBOTS_SOCCER_SIGHTINGS_MAX_LINE_T_INTERSECTION_SIGHTINGS 8
Definition at line 76 of file soccer_sightings.h.
Typedef Documentation
gu_soccer_sightings
typedef struct gu_soccer_sightings gu_soccer_sightings
Function Documentation
gu_soccer_sightings_equals()
bool gu_soccer_sightings_equals (const gu_soccer_sightings lhs, const gu_soccer_sightings rhs)
Definition at line 63 of file soccer_sightings.c.
References gu_soccer_sightings::ball, gu_soccer_sightings::genericGoalPost, gu_optional_ellipse_sighting_equals(), gu_optional_rectangle_sighting_equals(), gu_pixel_coordinate_equals(), gu_rectangle_sighting_equals(), gu_soccer_sightings::leftGoalPost, gu_soccer_sightings::lineCorners, gu_soccer_sightings::lineCrosses, gu_soccer_sightings::lines, gu_soccer_sightings::lineTIntersections, gu_soccer_sightings::numCorners, gu_soccer_sightings::numCrosses, gu_soccer_sightings::numLines, gu_soccer_sightings::numTIntersections, and gu_soccer_sightings::rightGoalPost.
gu_soccer_sightings_update_from_wb_vision_detection_goal()
void gu_soccer_sightings_update_from_wb_vision_detection_goal (gu_soccer_sightings * sightings, const struct wb_vision_detection_goal goal, const uint16_t resWidth, const uint16_t resHeight)
Definition at line 90 of file soccer_sightings.c.
References gu_soccer_sightings::genericGoalPost, gu_optional_rectangle_sighting::has_value, gu_soccer_sightings::leftGoalPost, gu_soccer_sightings::rightGoalPost, and wb_vision_detection_goal_post_to_opt_rectangle_sighting().
Referenced by gu_nao_update_from_wb_types().
gu_soccer_sightings_update_from_wb_vision_line_array()
void gu_soccer_sightings_update_from_wb_vision_line_array (gu_soccer_sightings * sightings, const struct wb_vision_line * lines, const int numLines, const uint16_t resWidth, const uint16_t resHeight)
Definition at line 128 of file soccer_sightings.c.
References GUROBOTS_SOCCER_SIGHTINGS_MAX_LINE_SIGHTINGS, gu_soccer_sightings::lines, gu_soccer_sightings::numLines, and wb_vision_line_to_rectangle_sighting().
Referenced by gu_nao_update_from_wb_types().