gurobots: GU::YawRollJoint Struct Reference
GU::YawRollJoint Struct Reference
#include <YawRollJoint.hpp>
Public Member Functions
YawRollJoint ()
YawRollJoint (const degrees_f, const degrees_f)
YawRollJoint (const YawRollJoint &other)
YawRollJoint (const gu_yaw_roll_joint &other)
YawRollJoint (YawRollJoint &&other)
~YawRollJoint ()
YawRollJoint & operator= (const YawRollJoint &other)
YawRollJoint & operator= (const gu_yaw_roll_joint &other)
YawRollJoint & operator= (YawRollJoint &&other)
degrees_f yaw () const
void set_yaw (const degrees_f)
degrees_f roll () const
void set_roll (const degrees_f)
Additional Inherited Members
Public Attributes inherited from gu_yaw_roll_joint
degrees_f yaw
degrees_f roll
Detailed Description
Definition at line 71 of file YawRollJoint.hpp.
Constructor & Destructor Documentation
YawRollJoint() [1/5]
GU::YawRollJoint::YawRollJoint ()
Definition at line 61 of file YawRollJoint.cc.
YawRollJoint() [2/5]
GU::YawRollJoint::YawRollJoint (const degrees_f t_yaw, const degrees_f t_roll)
Definition at line 63 of file YawRollJoint.cc.
YawRollJoint() [3/5]
GU::YawRollJoint::YawRollJoint (const YawRollJoint & other)
Definition at line 69 of file YawRollJoint.cc.
References roll(), and yaw().
YawRollJoint() [4/5]
GU::YawRollJoint::YawRollJoint (const gu_yaw_roll_joint & other)
Definition at line 75 of file YawRollJoint.cc.
References gu_yaw_roll_joint::roll, and gu_yaw_roll_joint::yaw.
YawRollJoint() [5/5]
GU::YawRollJoint::YawRollJoint (GU::YawRollJoint && other)
Definition at line 82 of file YawRollJoint.cc.
~YawRollJoint()
GU::YawRollJoint::~YawRollJoint ()
Definition at line 91 of file YawRollJoint.cc.
Member Function Documentation
operator=() [1/3]
GU::YawRollJoint & GU::YawRollJoint::operator= (const gu_yaw_roll_joint & other)
Definition at line 104 of file YawRollJoint.cc.
References gu_yaw_roll_joint::roll, and gu_yaw_roll_joint::yaw.
operator=() [2/3]
GU::YawRollJoint & GU::YawRollJoint::operator= (const YawRollJoint & other)
Definition at line 93 of file YawRollJoint.cc.
References roll(), and yaw().
operator=() [3/3]
GU::YawRollJoint & GU::YawRollJoint::operator= (GU::YawRollJoint && other)
Definition at line 116 of file YawRollJoint.cc.
roll()
degrees_f GU::YawRollJoint::roll () const
Definition at line 140 of file YawRollJoint.cc.
References gu_yaw_roll_joint::roll.
Referenced by YawRollJoint(), and operator=().
set_roll()
void GU::YawRollJoint::set_roll (const degrees_f newValue)
Definition at line 145 of file YawRollJoint.cc.
References gu_yaw_roll_joint::roll.
set_yaw()
void GU::YawRollJoint::set_yaw (const degrees_f newValue)
Definition at line 135 of file YawRollJoint.cc.
References gu_yaw_roll_joint::yaw.
yaw()
degrees_f GU::YawRollJoint::yaw () const
Definition at line 130 of file YawRollJoint.cc.
References gu_yaw_roll_joint::yaw.
Referenced by YawRollJoint(), and operator=().
The documentation for this struct was generated from the following files:
YawRollJoint.hpp
YawRollJoint.cc