gurobots: GU::PitchYawJoint Struct Reference
GU::PitchYawJoint Struct Reference
#include <PitchYawJoint.hpp>
Public Member Functions
PitchYawJoint ()
PitchYawJoint (const degrees_f, const degrees_f)
PitchYawJoint (const PitchYawJoint &other)
PitchYawJoint (const gu_pitch_yaw_joint &other)
PitchYawJoint (PitchYawJoint &&other)
~PitchYawJoint ()
PitchYawJoint & operator= (const PitchYawJoint &other)
PitchYawJoint & operator= (const gu_pitch_yaw_joint &other)
PitchYawJoint & operator= (PitchYawJoint &&other)
degrees_f pitch () const
void set_pitch (const degrees_f)
degrees_f yaw () const
void set_yaw (const degrees_f)
Additional Inherited Members
Public Attributes inherited from gu_pitch_yaw_joint
degrees_f pitch
degrees_f yaw
Detailed Description
Definition at line 71 of file PitchYawJoint.hpp.
Constructor & Destructor Documentation
PitchYawJoint() [1/5]
GU::PitchYawJoint::PitchYawJoint ()
Definition at line 61 of file PitchYawJoint.cc.
PitchYawJoint() [2/5]
GU::PitchYawJoint::PitchYawJoint (const degrees_f t_pitch, const degrees_f t_yaw)
Definition at line 63 of file PitchYawJoint.cc.
PitchYawJoint() [3/5]
GU::PitchYawJoint::PitchYawJoint (const PitchYawJoint & other)
Definition at line 69 of file PitchYawJoint.cc.
References pitch(), and yaw().
PitchYawJoint() [4/5]
GU::PitchYawJoint::PitchYawJoint (const gu_pitch_yaw_joint & other)
Definition at line 75 of file PitchYawJoint.cc.
References gu_pitch_yaw_joint::pitch, and gu_pitch_yaw_joint::yaw.
PitchYawJoint() [5/5]
GU::PitchYawJoint::PitchYawJoint (GU::PitchYawJoint && other)
Definition at line 82 of file PitchYawJoint.cc.
~PitchYawJoint()
GU::PitchYawJoint::~PitchYawJoint ()
Definition at line 91 of file PitchYawJoint.cc.
Member Function Documentation
operator=() [1/3]
GU::PitchYawJoint & GU::PitchYawJoint::operator= (const gu_pitch_yaw_joint & other)
Definition at line 104 of file PitchYawJoint.cc.
References gu_pitch_yaw_joint::pitch, and gu_pitch_yaw_joint::yaw.
operator=() [2/3]
GU::PitchYawJoint & GU::PitchYawJoint::operator= (const PitchYawJoint & other)
Definition at line 93 of file PitchYawJoint.cc.
References pitch(), and yaw().
operator=() [3/3]
GU::PitchYawJoint & GU::PitchYawJoint::operator= (GU::PitchYawJoint && other)
Definition at line 116 of file PitchYawJoint.cc.
pitch()
degrees_f GU::PitchYawJoint::pitch () const
Definition at line 130 of file PitchYawJoint.cc.
References gu_pitch_yaw_joint::pitch.
Referenced by PitchYawJoint(), and operator=().
set_pitch()
void GU::PitchYawJoint::set_pitch (const degrees_f newValue)
Definition at line 135 of file PitchYawJoint.cc.
References gu_pitch_yaw_joint::pitch.
set_yaw()
void GU::PitchYawJoint::set_yaw (const degrees_f newValue)
Definition at line 145 of file PitchYawJoint.cc.
References gu_pitch_yaw_joint::yaw.
yaw()
degrees_f GU::PitchYawJoint::yaw () const
Definition at line 140 of file PitchYawJoint.cc.
References gu_pitch_yaw_joint::yaw.
Referenced by PitchYawJoint(), and operator=().
The documentation for this struct was generated from the following files:
PitchYawJoint.hpp
PitchYawJoint.cc