gurobots: GU::PitchRollJoint Struct Reference
GU::PitchRollJoint Struct Reference
#include <PitchRollJoint.hpp>
Public Member Functions
PitchRollJoint ()
PitchRollJoint (const degrees_f, const degrees_f)
PitchRollJoint (const PitchRollJoint &other)
PitchRollJoint (const gu_pitch_roll_joint &other)
PitchRollJoint (PitchRollJoint &&other)
~PitchRollJoint ()
PitchRollJoint & operator= (const PitchRollJoint &other)
PitchRollJoint & operator= (const gu_pitch_roll_joint &other)
PitchRollJoint & operator= (PitchRollJoint &&other)
degrees_f pitch () const
void set_pitch (const degrees_f)
degrees_f roll () const
void set_roll (const degrees_f)
Additional Inherited Members
Public Attributes inherited from gu_pitch_roll_joint
degrees_f pitch
degrees_f roll
Detailed Description
Definition at line 71 of file PitchRollJoint.hpp.
Constructor & Destructor Documentation
PitchRollJoint() [1/5]
GU::PitchRollJoint::PitchRollJoint ()
Definition at line 61 of file PitchRollJoint.cc.
PitchRollJoint() [2/5]
GU::PitchRollJoint::PitchRollJoint (const degrees_f t_pitch, const degrees_f t_roll)
Definition at line 63 of file PitchRollJoint.cc.
PitchRollJoint() [3/5]
GU::PitchRollJoint::PitchRollJoint (const PitchRollJoint & other)
Definition at line 69 of file PitchRollJoint.cc.
References pitch(), and roll().
PitchRollJoint() [4/5]
GU::PitchRollJoint::PitchRollJoint (const gu_pitch_roll_joint & other)
Definition at line 75 of file PitchRollJoint.cc.
References gu_pitch_roll_joint::pitch, and gu_pitch_roll_joint::roll.
PitchRollJoint() [5/5]
GU::PitchRollJoint::PitchRollJoint (GU::PitchRollJoint && other)
Definition at line 82 of file PitchRollJoint.cc.
~PitchRollJoint()
GU::PitchRollJoint::~PitchRollJoint ()
Definition at line 91 of file PitchRollJoint.cc.
Member Function Documentation
operator=() [1/3]
GU::PitchRollJoint & GU::PitchRollJoint::operator= (const gu_pitch_roll_joint & other)
Definition at line 104 of file PitchRollJoint.cc.
References gu_pitch_roll_joint::pitch, and gu_pitch_roll_joint::roll.
operator=() [2/3]
GU::PitchRollJoint & GU::PitchRollJoint::operator= (const PitchRollJoint & other)
Definition at line 93 of file PitchRollJoint.cc.
References pitch(), and roll().
operator=() [3/3]
GU::PitchRollJoint & GU::PitchRollJoint::operator= (GU::PitchRollJoint && other)
Definition at line 116 of file PitchRollJoint.cc.
pitch()
degrees_f GU::PitchRollJoint::pitch () const
Definition at line 130 of file PitchRollJoint.cc.
References gu_pitch_roll_joint::pitch.
Referenced by PitchRollJoint(), and operator=().
roll()
degrees_f GU::PitchRollJoint::roll () const
Definition at line 140 of file PitchRollJoint.cc.
References gu_pitch_roll_joint::roll.
Referenced by PitchRollJoint(), and operator=().
set_pitch()
void GU::PitchRollJoint::set_pitch (const degrees_f newValue)
Definition at line 135 of file PitchRollJoint.cc.
References gu_pitch_roll_joint::pitch.
set_roll()
void GU::PitchRollJoint::set_roll (const degrees_f newValue)
Definition at line 145 of file PitchRollJoint.cc.
References gu_pitch_roll_joint::roll.
The documentation for this struct was generated from the following files:
PitchRollJoint.hpp
PitchRollJoint.cc