gurobots: GU::PitchJoint Struct Reference
GU::PitchJoint Struct Reference
#include <PitchJoint.hpp>
Public Member Functions
PitchJoint ()
PitchJoint (const degrees_f)
PitchJoint (const PitchJoint &other)
PitchJoint (const gu_pitch_joint &other)
PitchJoint (PitchJoint &&other)
~PitchJoint ()
PitchJoint & operator= (const PitchJoint &other)
PitchJoint & operator= (const gu_pitch_joint &other)
PitchJoint & operator= (PitchJoint &&other)
degrees_f pitch () const
void set_pitch (const degrees_f)
Additional Inherited Members
Public Attributes inherited from gu_pitch_joint
degrees_f pitch
Detailed Description
Definition at line 71 of file PitchJoint.hpp.
Constructor & Destructor Documentation
PitchJoint() [1/5]
GU::PitchJoint::PitchJoint ()
Definition at line 61 of file PitchJoint.cc.
PitchJoint() [2/5]
GU::PitchJoint::PitchJoint (const degrees_f t_pitch)
Definition at line 63 of file PitchJoint.cc.
PitchJoint() [3/5]
GU::PitchJoint::PitchJoint (const PitchJoint & other)
Definition at line 68 of file PitchJoint.cc.
References pitch().
PitchJoint() [4/5]
GU::PitchJoint::PitchJoint (const gu_pitch_joint & other)
Definition at line 73 of file PitchJoint.cc.
References gu_pitch_joint::pitch.
PitchJoint() [5/5]
GU::PitchJoint::PitchJoint (GU::PitchJoint && other)
Definition at line 79 of file PitchJoint.cc.
~PitchJoint()
GU::PitchJoint::~PitchJoint ()
Definition at line 86 of file PitchJoint.cc.
Member Function Documentation
operator=() [1/3]
GU::PitchJoint & GU::PitchJoint::operator= (const gu_pitch_joint & other)
Definition at line 98 of file PitchJoint.cc.
References gu_pitch_joint::pitch.
operator=() [2/3]
GU::PitchJoint & GU::PitchJoint::operator= (const PitchJoint & other)
Definition at line 88 of file PitchJoint.cc.
References pitch().
operator=() [3/3]
GU::PitchJoint & GU::PitchJoint::operator= (GU::PitchJoint && other)
Definition at line 109 of file PitchJoint.cc.
pitch()
degrees_f GU::PitchJoint::pitch () const
Definition at line 121 of file PitchJoint.cc.
References gu_pitch_joint::pitch.
Referenced by PitchJoint(), and operator=().
set_pitch()
void GU::PitchJoint::set_pitch (const degrees_f newValue)
Definition at line 126 of file PitchJoint.cc.
References gu_pitch_joint::pitch.
The documentation for this struct was generated from the following files:
PitchJoint.hpp
PitchJoint.cc