gurobots: GU::SoccerLocations Struct Reference
GU::SoccerLocations Struct Reference
#include <SoccerLocations.hpp>
Public Member Functions
SoccerLocations ()
SoccerLocations (const OptionalRelativeCoordinate, const OptionalRelativeCoordinate, const OptionalRelativeCoordinate, const OptionalRelativeCoordinate)
SoccerLocations (const std::optional< RelativeCoordinate >, const std::optional< RelativeCoordinate >, const std::optional< RelativeCoordinate >, const std::optional< RelativeCoordinate >)
SoccerLocations (const SoccerLocations &other)
SoccerLocations (const gu_soccer_locations &other)
SoccerLocations (SoccerLocations &&other)
~SoccerLocations ()
SoccerLocations & operator= (const SoccerLocations &other)
SoccerLocations & operator= (const gu_soccer_locations &other)
SoccerLocations & operator= (SoccerLocations &&other)
OptionalRelativeCoordinate rawBall () const
void set_rawBall (const OptionalRelativeCoordinate)
OptionalRelativeCoordinate rawLeftGoalPost () const
void set_rawLeftGoalPost (const OptionalRelativeCoordinate)
OptionalRelativeCoordinate rawRightGoalPost () const
void set_rawRightGoalPost (const OptionalRelativeCoordinate)
OptionalRelativeCoordinate rawGoal () const
void set_rawGoal (const OptionalRelativeCoordinate)
std::optional< RelativeCoordinate > ball () const
void set_ball (const std::optional< RelativeCoordinate >)
std::optional< RelativeCoordinate > leftGoalPost () const
void set_leftGoalPost (const std::optional< RelativeCoordinate >)
std::optional< RelativeCoordinate > rightGoalPost () const
void set_rightGoalPost (const std::optional< RelativeCoordinate >)
std::optional< RelativeCoordinate > goal () const
void set_goal (const std::optional< RelativeCoordinate >)
Additional Inherited Members
Public Attributes inherited from gu_soccer_locations
gu_optional_relative_coordinate ball
gu_optional_relative_coordinate leftGoalPost
gu_optional_relative_coordinate rightGoalPost
gu_optional_relative_coordinate goal
Detailed Description
Definition at line 75 of file SoccerLocations.hpp.
Constructor & Destructor Documentation
SoccerLocations() [1/6]
GU::SoccerLocations::SoccerLocations ()
Definition at line 61 of file SoccerLocations.cc.
SoccerLocations() [2/6]
GU::SoccerLocations::SoccerLocations (const OptionalRelativeCoordinate, const OptionalRelativeCoordinate, const OptionalRelativeCoordinate, const OptionalRelativeCoordinate)
SoccerLocations() [3/6]
GU::SoccerLocations::SoccerLocations (const std::optional< RelativeCoordinate > , const std::optional< RelativeCoordinate > , const std::optional< RelativeCoordinate > , const std::optional< RelativeCoordinate >)
SoccerLocations() [4/6]
GU::SoccerLocations::SoccerLocations (const SoccerLocations & other)
Definition at line 81 of file SoccerLocations.cc.
References rawBall(), rawGoal(), rawLeftGoalPost(), and rawRightGoalPost().
SoccerLocations() [5/6]
GU::SoccerLocations::SoccerLocations (const gu_soccer_locations & other)
Definition at line 89 of file SoccerLocations.cc.
References gu_soccer_locations::ball, gu_soccer_locations::goal, gu_soccer_locations::leftGoalPost, and gu_soccer_locations::rightGoalPost.
SoccerLocations() [6/6]
GU::SoccerLocations::SoccerLocations (GU::SoccerLocations && other)
Definition at line 98 of file SoccerLocations.cc.
~SoccerLocations()
GU::SoccerLocations::~SoccerLocations ()
Definition at line 111 of file SoccerLocations.cc.
Member Function Documentation
ball()
std::optional< GU::RelativeCoordinate > GU::SoccerLocations::ball () const
Definition at line 199 of file SoccerLocations.cc.
References gu_soccer_locations::ball.
goal()
std::optional< GU::RelativeCoordinate > GU::SoccerLocations::goal () const
Definition at line 229 of file SoccerLocations.cc.
References gu_soccer_locations::goal.
leftGoalPost()
std::optional< GU::RelativeCoordinate > GU::SoccerLocations::leftGoalPost () const
Definition at line 209 of file SoccerLocations.cc.
References gu_soccer_locations::leftGoalPost.
operator=() [1/3]
GU::SoccerLocations & GU::SoccerLocations::operator= (const gu_soccer_locations & other)
Definition at line 126 of file SoccerLocations.cc.
References gu_soccer_locations::ball, gu_soccer_locations::goal, gu_soccer_locations::leftGoalPost, and gu_soccer_locations::rightGoalPost.
operator=() [2/3]
GU::SoccerLocations & GU::SoccerLocations::operator= (const SoccerLocations & other)
Definition at line 113 of file SoccerLocations.cc.
References rawBall(), rawGoal(), rawLeftGoalPost(), and rawRightGoalPost().
operator=() [3/3]
GU::SoccerLocations & GU::SoccerLocations::operator= (GU::SoccerLocations && other)
Definition at line 140 of file SoccerLocations.cc.
rawBall()
GU::OptionalRelativeCoordinate GU::SoccerLocations::rawBall () const
Definition at line 158 of file SoccerLocations.cc.
References gu_soccer_locations::ball.
Referenced by SoccerLocations(), and operator=().
rawGoal()
GU::OptionalRelativeCoordinate GU::SoccerLocations::rawGoal () const
Definition at line 188 of file SoccerLocations.cc.
References gu_soccer_locations::goal.
Referenced by SoccerLocations(), and operator=().
rawLeftGoalPost()
GU::OptionalRelativeCoordinate GU::SoccerLocations::rawLeftGoalPost () const
Definition at line 168 of file SoccerLocations.cc.
References gu_soccer_locations::leftGoalPost.
Referenced by SoccerLocations(), and operator=().
rawRightGoalPost()
GU::OptionalRelativeCoordinate GU::SoccerLocations::rawRightGoalPost () const
Definition at line 178 of file SoccerLocations.cc.
References gu_soccer_locations::rightGoalPost.
Referenced by SoccerLocations(), and operator=().
rightGoalPost()
std::optional< GU::RelativeCoordinate > GU::SoccerLocations::rightGoalPost () const
Definition at line 219 of file SoccerLocations.cc.
References gu_soccer_locations::rightGoalPost.
set_ball()
void GU::SoccerLocations::set_ball (const std::optional< RelativeCoordinate >)
Definition at line 204 of file SoccerLocations.cc.
References gu_soccer_locations::ball.
set_goal()
void GU::SoccerLocations::set_goal (const std::optional< RelativeCoordinate >)
Definition at line 234 of file SoccerLocations.cc.
References gu_soccer_locations::goal.
set_leftGoalPost()
void GU::SoccerLocations::set_leftGoalPost (const std::optional< RelativeCoordinate >)
Definition at line 214 of file SoccerLocations.cc.
References gu_soccer_locations::leftGoalPost.
set_rawBall()
void GU::SoccerLocations::set_rawBall (const OptionalRelativeCoordinate)
Definition at line 163 of file SoccerLocations.cc.
References gu_soccer_locations::ball.
set_rawGoal()
void GU::SoccerLocations::set_rawGoal (const OptionalRelativeCoordinate)
Definition at line 193 of file SoccerLocations.cc.
References gu_soccer_locations::goal.
set_rawLeftGoalPost()
void GU::SoccerLocations::set_rawLeftGoalPost (const OptionalRelativeCoordinate)
Definition at line 173 of file SoccerLocations.cc.
References gu_soccer_locations::leftGoalPost.
set_rawRightGoalPost()
void GU::SoccerLocations::set_rawRightGoalPost (const OptionalRelativeCoordinate)
Definition at line 183 of file SoccerLocations.cc.
References gu_soccer_locations::rightGoalPost.
set_rightGoalPost()
void GU::SoccerLocations::set_rightGoalPost (const std::optional< RelativeCoordinate >)
Definition at line 224 of file SoccerLocations.cc.
References gu_soccer_locations::rightGoalPost.
The documentation for this struct was generated from the following files:
SoccerLocations.hpp
SoccerLocations.cc