gurobots: GU::YPJoint Struct Reference
GU::YPJoint Struct Reference
#include <YPJoint.hpp>
Public Member Functions
YPJoint ()
YPJoint (const degrees_f, const degrees_f)
YPJoint (const YPJoint &other)
YPJoint (const gu_yp_joint &other)
YPJoint (YPJoint &&other)
~YPJoint ()
YPJoint & operator= (const YPJoint &other)
YPJoint & operator= (const gu_yp_joint &other)
YPJoint & operator= (YPJoint &&other)
degrees_f pitch () const
void set_pitch (const degrees_f)
degrees_f roll () const
void set_roll (const degrees_f)
degrees_f yawPitch () const
void set_yawPitch (const degrees_f)
Additional Inherited Members
Public Attributes inherited from gu_yp_joint
degrees_f pitch
degrees_f roll
degrees_f yawPitch
Detailed Description
Definition at line 71 of file YPJoint.hpp.
Constructor & Destructor Documentation
YPJoint() [1/5]
GU::YPJoint::YPJoint ()
Definition at line 61 of file YPJoint.cc.
YPJoint() [2/5]
GU::YPJoint::YPJoint (const degrees_f t_pitch, const degrees_f t_roll)
Definition at line 63 of file YPJoint.cc.
YPJoint() [3/5]
GU::YPJoint::YPJoint (const YPJoint & other)
Definition at line 69 of file YPJoint.cc.
References pitch(), and roll().
YPJoint() [4/5]
GU::YPJoint::YPJoint (const gu_yp_joint & other)
Definition at line 75 of file YPJoint.cc.
References gu_yp_joint::pitch, and gu_yp_joint::roll.
YPJoint() [5/5]
GU::YPJoint::YPJoint (GU::YPJoint && other)
Definition at line 82 of file YPJoint.cc.
~YPJoint()
GU::YPJoint::~YPJoint ()
Definition at line 91 of file YPJoint.cc.
Member Function Documentation
operator=() [1/3]
GU::YPJoint & GU::YPJoint::operator= (const gu_yp_joint & other)
Definition at line 104 of file YPJoint.cc.
References gu_yp_joint::pitch, and gu_yp_joint::roll.
operator=() [2/3]
GU::YPJoint & GU::YPJoint::operator= (const YPJoint & other)
Definition at line 93 of file YPJoint.cc.
References pitch(), and roll().
operator=() [3/3]
GU::YPJoint & GU::YPJoint::operator= (GU::YPJoint && other)
Definition at line 116 of file YPJoint.cc.
pitch()
degrees_f GU::YPJoint::pitch () const
Definition at line 130 of file YPJoint.cc.
References gu_yp_joint::pitch.
Referenced by YPJoint(), and operator=().
roll()
degrees_f GU::YPJoint::roll () const
Definition at line 140 of file YPJoint.cc.
References gu_yp_joint::roll.
Referenced by YPJoint(), and operator=().
set_pitch()
void GU::YPJoint::set_pitch (const degrees_f newValue)
Definition at line 135 of file YPJoint.cc.
References gu_yp_joint::pitch.
set_roll()
void GU::YPJoint::set_roll (const degrees_f newValue)
Definition at line 145 of file YPJoint.cc.
References gu_yp_joint::roll.
set_yawPitch()
void GU::YPJoint::set_yawPitch (const degrees_f newValue)
Definition at line 155 of file YPJoint.cc.
References gu_yp_joint::yawPitch.
yawPitch()
degrees_f GU::YPJoint::yawPitch () const
Definition at line 150 of file YPJoint.cc.
References gu_yp_joint::yawPitch.
The documentation for this struct was generated from the following files:
YPJoint.hpp
YPJoint.cc