gurobots: GU::NaoV5 Struct Reference
GU::NaoV5 Struct Reference
#include <NaoV5.hpp>
Public Member Functions
NaoV5 ()
NaoV5 (gu_simple_whiteboard *wb)
NaoV5 (const NaoV5 &other)
NaoV5 (NaoV5 &&other)
~NaoV5 ()
NaoV5 & operator= (const NaoV5 &other)
NaoV5 & operator= (NaoV5 &&other)
gu_nao_joints joints () const
gu_soccer_locations locations () const
GU::CameraPivot cameraPivot () const
bool fieldPosition (GU::FieldCoordinate &) const
bool ballSighting (GU::RelativeCoordinate &) const
bool leftGoalPostSighting (GU::RelativeCoordinate &) const
bool rightGoalPostSighting (GU::RelativeCoordinate &) const
bool goalSighting (GU::RelativeCoordinate &) const
std::optional< GU::FieldCoordinate > fieldPosition () const
std::optional< GU::RelativeCoordinate > ballSighting () const
std::optional< GU::RelativeCoordinate > leftGoalPostSighting () const
std::optional< GU::RelativeCoordinate > rightGoalPostSighting () const
std::optional< GU::RelativeCoordinate > goalSighting () const
std::optional< RelativeCoordinate > topCameraRelativeCoordinate (const GU::CameraCoordinate &)
std::optional< RelativeCoordinate > topCameraRelativeCoordinate (const GU::PixelCoordinate &)
std::optional< RelativeCoordinate > topCameraRelativeCoordinate (const GU::PercentCoordinate &)
std::optional< RelativeCoordinate > bottomCameraRelativeCoordinate (const GU::CameraCoordinate &)
std::optional< RelativeCoordinate > bottomCameraRelativeCoordinate (const GU::PixelCoordinate &)
std::optional< RelativeCoordinate > bottomCameraRelativeCoordinate (const GU::PercentCoordinate &)
void update ()
Additional Inherited Members
Public Attributes inherited from gu_nao
uint8_t playerNumber
gu_optional_field_coordinate fieldPosition
gu_optional_ball_position ballPosition
gu_nao_joints joints
gu_soccer_locations locations
gu_soccer_sightings topCameraSightings
gu_soccer_sightings bottomCameraSightings
Detailed Description
Definition at line 76 of file NaoV5.hpp.
Constructor & Destructor Documentation
NaoV5() [1/4]
GU::NaoV5::NaoV5 ()
Definition at line 69 of file NaoV5.cc.
References update().
NaoV5() [2/4]
GU::NaoV5::NaoV5 (gu_simple_whiteboard * wb)
Definition at line 74 of file NaoV5.cc.
NaoV5() [3/4]
GU::NaoV5::NaoV5 (const NaoV5 & other)
Definition at line 80 of file NaoV5.cc.
References gu_nao::fieldPosition, gu_nao::joints, and gu_nao::locations.
NaoV5() [4/4]
GU::NaoV5::NaoV5 (NaoV5 && other)
Definition at line 90 of file NaoV5.cc.
References gu_nao::fieldPosition, gu_nao_empty(), gu_nao::joints, and gu_nao::locations.
~NaoV5()
GU::NaoV5::~NaoV5 ()
Definition at line 101 of file NaoV5.cc.
Member Function Documentation
ballSighting() [1/2]
std::optional< GU::RelativeCoordinate > GU::NaoV5::ballSighting () const
Definition at line 193 of file NaoV5.cc.
References gu_nao::locations.
ballSighting() [2/2]
bool GU::NaoV5::ballSighting (GU::RelativeCoordinate & coordinate) const
Definition at line 153 of file NaoV5.cc.
References gu_soccer_locations::ball, and gu_nao::locations.
bottomCameraRelativeCoordinate() [1/3]
std::optional< GU::RelativeCoordinate > GU::NaoV5::bottomCameraRelativeCoordinate (const GU::CameraCoordinate & coordinate)
Definition at line 236 of file NaoV5.cc.
References GU_NAO_V5_BOTTOM_CAMERA_INDEX.
bottomCameraRelativeCoordinate() [2/3]
std::optional< GU::RelativeCoordinate > GU::NaoV5::bottomCameraRelativeCoordinate (const GU::PercentCoordinate & coordinate)
Definition at line 246 of file NaoV5.cc.
References GU_NAO_V5_BOTTOM_CAMERA_INDEX.
bottomCameraRelativeCoordinate() [3/3]
std::optional< GU::RelativeCoordinate > GU::NaoV5::bottomCameraRelativeCoordinate (const GU::PixelCoordinate & coordinate)
Definition at line 241 of file NaoV5.cc.
References GU_NAO_V5_BOTTOM_CAMERA_INDEX.
cameraPivot()
GU::CameraPivot GU::NaoV5::cameraPivot () const
Definition at line 130 of file NaoV5.cc.
References gu_nao_head_to_camera_pivot(), and gu_nao::joints.
fieldPosition() [1/2]
std::optional< GU::FieldCoordinate > GU::NaoV5::fieldPosition () const
Definition at line 186 of file NaoV5.cc.
References gu_nao::fieldPosition.
fieldPosition() [2/2]
bool GU::NaoV5::fieldPosition (GU::FieldCoordinate & coordinate) const
Definition at line 145 of file NaoV5.cc.
References gu_nao::fieldPosition.
goalSighting() [1/2]
std::optional< GU::RelativeCoordinate > GU::NaoV5::goalSighting () const
Definition at line 214 of file NaoV5.cc.
References gu_nao::locations.
goalSighting() [2/2]
bool GU::NaoV5::goalSighting (GU::RelativeCoordinate & coordinate) const
Definition at line 177 of file NaoV5.cc.
References gu_soccer_locations::goal, and gu_nao::locations.
joints()
gu_nao_joints GU::NaoV5::joints () const
Definition at line 135 of file NaoV5.cc.
References gu_nao::joints.
leftGoalPostSighting() [1/2]
std::optional< GU::RelativeCoordinate > GU::NaoV5::leftGoalPostSighting () const
Definition at line 200 of file NaoV5.cc.
References gu_nao::locations.
leftGoalPostSighting() [2/2]
bool GU::NaoV5::leftGoalPostSighting (GU::RelativeCoordinate & coordinate) const
Definition at line 161 of file NaoV5.cc.
References gu_soccer_locations::leftGoalPost, and gu_nao::locations.
locations()
gu_soccer_locations GU::NaoV5::locations () const
Definition at line 140 of file NaoV5.cc.
References gu_nao::locations.
operator=() [1/2]
GU::NaoV5 & GU::NaoV5::operator= (const NaoV5 & other)
Definition at line 103 of file NaoV5.cc.
References gu_nao::fieldPosition, gu_nao::joints, and gu_nao::locations.
operator=() [2/2]
GU::NaoV5 & GU::NaoV5::operator= (GU::NaoV5 && other)
Definition at line 115 of file NaoV5.cc.
References gu_nao::fieldPosition, gu_nao_empty(), gu_nao::joints, and gu_nao::locations.
rightGoalPostSighting() [1/2]
std::optional< GU::RelativeCoordinate > GU::NaoV5::rightGoalPostSighting () const
Definition at line 207 of file NaoV5.cc.
References gu_nao::locations.
rightGoalPostSighting() [2/2]
bool GU::NaoV5::rightGoalPostSighting (GU::RelativeCoordinate & coordinate) const
Definition at line 169 of file NaoV5.cc.
References gu_nao::locations, and gu_soccer_locations::rightGoalPost.
topCameraRelativeCoordinate() [1/3]
std::optional< GU::RelativeCoordinate > GU::NaoV5::topCameraRelativeCoordinate (const GU::CameraCoordinate & coordinate)
Definition at line 221 of file NaoV5.cc.
References GU_NAO_V5_TOP_CAMERA_INDEX.
topCameraRelativeCoordinate() [2/3]
std::optional< GU::RelativeCoordinate > GU::NaoV5::topCameraRelativeCoordinate (const GU::PercentCoordinate & coordinate)
Definition at line 231 of file NaoV5.cc.
References GU_NAO_V5_TOP_CAMERA_INDEX.
topCameraRelativeCoordinate() [3/3]
std::optional< GU::RelativeCoordinate > GU::NaoV5::topCameraRelativeCoordinate (const GU::PixelCoordinate & coordinate)
Definition at line 226 of file NaoV5.cc.
References GU_NAO_V5_TOP_CAMERA_INDEX.
update()
void GU::NaoV5::update ()
Definition at line 257 of file NaoV5.cc.
References gu_nao_update_from_wb().
Referenced by NaoV5(), CGTEST::NaoV5CPPTests::change(), and CGTEST::NaoV5CPPTests::initial().
The documentation for this struct was generated from the following files:
NaoV5.hpp
NaoV5.cc