gurobots: GU::YawJoint Struct Reference
GU::YawJoint Struct Reference
#include <YawJoint.hpp>
Public Member Functions
YawJoint ()
YawJoint (const degrees_f)
YawJoint (const YawJoint &other)
YawJoint (const gu_yaw_joint &other)
YawJoint (YawJoint &&other)
~YawJoint ()
YawJoint & operator= (const YawJoint &other)
YawJoint & operator= (const gu_yaw_joint &other)
YawJoint & operator= (YawJoint &&other)
degrees_f yaw () const
void set_yaw (const degrees_f)
Additional Inherited Members
Public Attributes inherited from gu_yaw_joint
degrees_f yaw
Detailed Description
Definition at line 71 of file YawJoint.hpp.
Constructor & Destructor Documentation
YawJoint() [1/5]
GU::YawJoint::YawJoint ()
Definition at line 61 of file YawJoint.cc.
YawJoint() [2/5]
GU::YawJoint::YawJoint (const degrees_f t_yaw)
Definition at line 63 of file YawJoint.cc.
YawJoint() [3/5]
GU::YawJoint::YawJoint (const YawJoint & other)
Definition at line 68 of file YawJoint.cc.
References yaw().
YawJoint() [4/5]
GU::YawJoint::YawJoint (const gu_yaw_joint & other)
Definition at line 73 of file YawJoint.cc.
References gu_yaw_joint::yaw.
YawJoint() [5/5]
GU::YawJoint::YawJoint (GU::YawJoint && other)
Definition at line 79 of file YawJoint.cc.
~YawJoint()
GU::YawJoint::~YawJoint ()
Definition at line 86 of file YawJoint.cc.
Member Function Documentation
operator=() [1/3]
GU::YawJoint & GU::YawJoint::operator= (const gu_yaw_joint & other)
Definition at line 98 of file YawJoint.cc.
References gu_yaw_joint::yaw.
operator=() [2/3]
GU::YawJoint & GU::YawJoint::operator= (const YawJoint & other)
Definition at line 88 of file YawJoint.cc.
References yaw().
operator=() [3/3]
GU::YawJoint & GU::YawJoint::operator= (GU::YawJoint && other)
Definition at line 109 of file YawJoint.cc.
set_yaw()
void GU::YawJoint::set_yaw (const degrees_f newValue)
Definition at line 126 of file YawJoint.cc.
References gu_yaw_joint::yaw.
yaw()
degrees_f GU::YawJoint::yaw () const
Definition at line 121 of file YawJoint.cc.
References gu_yaw_joint::yaw.
Referenced by YawJoint(), and operator=().
The documentation for this struct was generated from the following files:
YawJoint.hpp
YawJoint.cc