name: Documentation

on:
  push:
    branches: [ main ]

jobs:
  build-documentation:
    runs-on: ubuntu-latest

    steps:

      - name: Install Ninja
        run: sudo apt install ninja-build

      - name: Install libdispatch
        run: sudo apt install libdispatch-dev

      - name: Clone gu_util
        uses: actions/checkout@v2
        with:
          repository: mipalgu/gu_util
          path: gu_util

      - name: Install gu_util
        run: |
          cd gu_util
          mkdir build
          cd build
          cmake -G Ninja ..
          ninja
          sudo ninja install

      - name: Clone guunits
        uses: actions/checkout@v2
        with:
          repository: mipalgu/guunits
          path: guunits

      - name: Install guunits
        run: |
          cd guunits/guunits
          mkdir build
          cd build
          cmake -G Ninja ..
          ninja
          sudo ninja install

      - name: Clone gucoordinates
        uses: actions/checkout@v2
        with:
          repository: mipalgu/gucoordinates
          path: gucoordinates

      - name: Install gucoordinates
        run: |
          cd gucoordinates/gucoordinates
          mkdir build
          cd build
          cmake -G Ninja ..
          ninja
          sudo ninja install

      - name: Clone guvision_utils
        uses: actions/checkout@v2
        with:
          repository: mipalgu/guvision_utils
          path: guvision_utils

      - name: Install guvision_utils
        run: |
          cd guvision_utils
          mkdir build
          cd build
          cmake -G Ninja ..
          ninja
          sudo ninja install

      - name: Clone gusimplewhiteboard
        uses: actions/checkout@v2
        with:
          repository: mipalgu/gusimplewhiteboard
          path: gusimplewhiteboard

      - name: Install gusimplewhiteboard
        run: |
          cd gusimplewhiteboard
          mkdir build
          cd build
          cmake -G Ninja ..
          ninja
          sudo ninja install

      - name: clone gurobots
        uses: actions/checkout@v2
        with:
          repository: mipalgu/gurobots
          path: gurobots

      - name: Clone theme
        uses: actions/checkout@v2
        with:
          repository: jothepro/doxygen-awesome-css.git
          ref: v1.5.0
          path: doxygen-awesome-css

      - name: Add theme to Doxyfile
        run: |
          sed -e 's|HTML_EXTRA_STYLESHEET .*|HTML_EXTRA_STYLESHEET = ../../doxygen-awesome-css/doxygen-awesome.css ../../doxygen-awesome-css/doxygen-awesome-sidebar-only.css|' -e 's|DOT_TRANSPARENT.*|DOT_TRANSPARENT = YES|' -e 's|DOT_IMAGE_FORMAT.*|DOT_IMAGE_FORMAT = svg|' -e 's|HTML_COLORSTYLE_GAMMA.*|HTML_COLORSTYLE_GAMMA = 113|' -e 's|HTML_COLORSTYLE_SAT.*|HTML_COLORSTYLE_SAT = 255|' -e 's|HTML_COLORSTYLE_HUE.*|HTML_COLORSTYLE_HUE = 209|' -e 's|GENERATE_TREEVIEW.*|GENERATE_TREEVIEW = YES|' < gurobots/gurobots/Doxyfile > gurobots/gurobots/Doxyfile.awesome

      - name: Doxygen
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          doxyfile-path: ./Doxyfile.awesome
          working-directory: ./gurobots/gurobots

      - name: Page Deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{github.workspace}}/gurobots/gurobots/documentation/html
